<?php

// TCP客户端
namespace app\common\command\swoole;

use function \Swoole\Coroutine\run;
use \Swoole\Coroutine\Client;
use think\console\Command;
use think\console\Input;
use think\console\Output;
use think\facade\Log;

class HTTPClient extends Command
{
    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
        $this->setName('tcp_client');
    }

    protected function execute(Input $input, Output $output)
    {
        run(function () {
            $client = new Client(config('app.swoole.host'), 80);
            $client->setHeaders([
                'Host' => config('app.swoole.host'),
                'User-Agent' => 'Chrome/49.0.2587.3',
                'Accept' => 'text/html,application/xhtml+xml,application/xml',
                'Accept-Encoding' => 'gzip',
            ]);
            $client->set(['timeout' => 1]);
            $client->get('/index.php');
            echo $client->body;
            $client->close();
        });
    }

}
