<?php

// TCP
namespace app\common\command\swoole;

use think\console\Command;
use think\console\Input;
use think\console\Output;
use think\facade\Log;

class HTTP extends Command
{
    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
        $this->setName('http');
    }

    protected function execute(Input $input, Output $output)
    {
        // 创建Http对象，监听 0.0.0.0:9501 端口，0.0.0.0 表示监听所有 IP 地址
        $http = new \Swoole\Http\Server('0.0.0.0', config('app.swoole.port_tcp'));

        // 用于设置运行时的各项参数
        // 需要先开启这里的程序，再去浏览器打开static里的akali.html
        $http->set([
            // 静态文件
            'enable_static_handler'  => true,
            // 根目录，放置html等其它的静态文件，直接访问
            'document_root' => '/var/www/www.ruiwen.com/app/common/command/swoole/static',
        ]);

        $http->on('Request', [$this, 'onRequest']);

        //启动服务器
        $http->start();
    }

    // $response->end() 方法表示输出一段 HTML 内容
    public function onRequest($request, $response)
    {
        // 使用 Chrome 浏览器访问服务器，会产生额外的一次请求，/favicon.ico，可以在代码中响应 404 错误。
        /* if ($request->server['path_info'] == '/favicon.ico' || $request->server['request_uri'] == '/favicon.ico') {
            $response->end();
            return;
        } */

        // 服务端打印 get、post 的请求参数
        var_dump($request->get, $request->post);
        
        $response->header('Content-Type', 'text/html; charset=utf-8');
        // $response->end('<h1>Hello Swoole. #' . rand(1000, 9999) . '</h1>');
        // $response->end('接收到的数据：' . json_encode($request->get));
        $response->end('接收到的数据：' . json_encode($request->post));
    }

}
