<?php

// UDP服务端
namespace app\common\command\swoole;

use think\console\Command;
use think\console\Input;
use think\console\Output;
use think\facade\Log;

class UDP extends Command
{
    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
        $this->setName('udp');
    }

    protected function execute(Input $input, Output $output)
    {
        // 创建Server对象，监听 127.0.0.1:9502 端口
        // 参数4：类型为UDP
        $server = new \Swoole\Server(config('app.swoole.host'), config('app.swoole.port_udp'), SWOOLE_PROCESS, SWOOLE_SOCK_UDP);

        // 用于设置运行时的各项参数
        $server->set([
            'worker_num'  => 4, // 进程数，最好是cpu核数的1-4倍
            'max_request' => 50, // 最大请求数
        ]);

        // 监听数据接收事件
        $server->on('Packet', [$this, 'onPacket']);

        //启动服务器
        $server->start();
    }

    // 监听数据接收事件
    public function onPacket($server, $data, $clientInfo)
    {
        var_dump($clientInfo);
        $server->sendto($clientInfo['address'], $clientInfo['port'], "服务端接收到的消息：{$data}");
    }

}
