<?php

// 发布确认 - 高级 备用交换机 这个老师没做
namespace app\common\command;

use app\common\lib\classes\rabbitmq\RabbitMqConnection;
use think\console\Command;
use think\console\Input;
use think\console\Output;
use think\facade\Log;

class ConfirmBackup extends Command
{
    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
        $this->setName('confirm_backup');
    }

    protected function execute(Input $input, Output $output)
    {
        // 弹幕：此处就是测试 交换机无法路由到队列 而转发给备份交换机的过程，正常情况用于备份数据的交换机肯定在备份服务器，这样测试不满意的话可以自己搭建集群测试。
        // 获取连接
        $connection = RabbitMqConnection::getConnection();
        // 获取消息通道
        $channel = $connection->channel();

        // 备份交换姬名称
        $backup_exchange = 'backup_exchange';
        // 备用队列
        $backup_queue = 'backup_queue';
    }

}
