<?php

// 死信队列练习 - 死信消费者
namespace app\common\command;

use app\common\lib\classes\rabbitmq\RabbitMqConnection;
use PhpAmqpLib\Wire\AMQPTable;
use think\console\Command;
use think\console\Input;
use think\console\Output;
use think\facade\Log;

class Delayed extends Command
{
    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
        $this->setName('delayed');
    }

    protected function execute(Input $input, Output $output)
    {
        // 连接
        $connection = RabbitMqConnection::getConnection();
        // 信息通道
        $channel = $connection->channel();

        // 死信队列名称
        $delayed_queue = 'delayed_queue';
        // 死信交换机名称
        $delayed_exchange = 'delayed_exchange';
        // 死信routing_key
        $delayed_routing_key = 'delayed_routing_key';

        // 
    }

}
