<?php
/**
 * 接收(直接交换机)
 * @param \Closure $callback
 * @param array $bindingKeys
 */
 
namespace app\common\command;
 
use app\common\lib\classes\RabbitMq;
use app\common\lib\classes\RabbitMqWork;
use think\console\Command;
use think\console\Input;
use think\console\Output;
 
class DirectQueue extends Command
{
    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
        $this->setName('directQueue');
    }
 
    protected function execute(Input $input, Output $output)
    {
        $RabbitMqWork = new RabbitMqWork(RabbitMq::DIRECT);
        $callback = function ($msg){
            echo "[x] ".$msg->delivery_info['routing_key'].":$msg->body \n";
        };
        $RabbitMqWork->receiveDirect($callback,RabbitMq::SEVERITYS);
    }
}