<?php
/**
 * 订阅(扇形交换机) 
 * @param $callback
 */

namespace app\common\command;

use app\common\lib\classes\rabbitmq\RabbitMq;
use app\common\lib\classes\rabbitmq\RabbitMqWork;
use think\console\Command;
use think\console\Input;
use think\console\Output;
use think\facade\Log;

class SendQueue extends Command
{
    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
        $this->setName('sendQueue');
    }

    protected function execute(Input $input, Output $output)
    {
        $RabbitMqWork = new RabbitMqWork(RabbitMq::FANOUT);
        $callback     = function ($msg) {
            // echo '消费者1-';
            // echo '消费者2-';
            echo '消费者3-';
            echo 'Receive: ';
            echo "$msg->body \n";
            // 保存到日志，这里可以用于日后错误日志的保存
            Log::error("Msg:$msg->body");
        };
        $RabbitMqWork->subscribeQueue($callback);
    }
}
