<?php
/**
 * 接收(普通)
 * @param $callback
 */

namespace app\common\command;

use app\common\lib\classes\rabbitmq\RabbitMqWork;
use think\console\Command;
use think\console\Input;
use think\console\Output;
use think\Log;

class SimpleWork extends Command
{
    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
        $this->setName('simpleWork');
    }

    protected function execute(Input $input, Output $output)
    {
        $RabbitMqWork = new RabbitMqWork();
        $callback     = function ($msg) {
            echo 'Receive:';
            $queueName = $msg->delivery_info['routing_key'];
            $msgData   = $msg->body;
            $isAck     = true;
            echo 'Msg:' . $msgData . "\n";
            echo 'QueueName:' . $queueName . "\n";
            // 如过调用接受方法：receive的basic_consume()函数里面的no_ack参数是true
            // 那么下面这里可以注释掉，因为已经进行了消息确认，不需要再次消息确认
            /* if ($isAck) {
                $msg->delivery_info['channel']->basic_ack($msg->delivery_info['delivery_tag']);
            } */
        };
        $RabbitMqWork->receive($callback);
    }
}
