<?php
/**
 * 接收(普通) 最简单队列
 * @param $callback
 */

namespace app\common\command;

use app\common\lib\classes\rabbitmq\RabbitMqWork;
use think\console\Command;
use think\console\Input;
use think\console\Output;
use think\Log;

class SimpleQueue extends Command
{
    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
        $this->setName('simpleQueue');
    }

    protected function execute(Input $input, Output $output)
    {
        $RabbitMqWork = new RabbitMqWork();
        $callback     = function ($msg) {
            // echo 'Receive:';
            echo "[x] 消费者-1：", "\n";
            // echo "[x] 消费者-2：", "\n";
            $queueName = $msg->delivery_info['routing_key'];
            $msgData   = $msg->body;
            $isAck     = true;
            echo 'Msg:' . $msgData . "\n";
            echo 'QueueName:' . $queueName . "\n";
            if ($isAck) {
                $msg->delivery_info['channel']->basic_ack($msg->delivery_info['delivery_tag']);
            }
        };
        $RabbitMqWork->receive($callback);
    }
}
