<?php
/**
 * 接收(主题交换机)
 * @param \Closure $callback
 * @param array $bindingKeys
 */

namespace app\common\command;

use app\common\lib\classes\rabbitmq\RabbitMq;
use app\common\lib\classes\rabbitmq\RabbitMqWork;
use think\console\Command;
use think\console\Input;
use think\console\Output;

class TopicQueue extends Command
{
    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
        $this->setName('topicQueue');
    }

    protected function execute(Input $input, Output $output)
    {
        $RabbitMqWork = new RabbitMqWork(RabbitMq::TOPIC);
        $callback     = function ($msg) {
            // echo '[x] ', $msg->delivery_info['routing_key'], ':', $msg->body, "\n";
            echo "[x] 消费者1\n";
            // echo "[x] 消费者2\n";
            echo '[x] 路由键: ', $msg->delivery_info['routing_key'], "\n";
            echo '[x] 消息: ', $msg->body, "\n";
            echo '[x] --------------------------------', "\n";
        };
        $bindingKeys = [
            'user.*',
            '*.orange.*',
            '*.*.rabbit',
            // 'lazy.#',
        ];
        $RabbitMqWork->receiveTopic($callback, $bindingKeys);
    }
}
