<?php

// 镜像集群
namespace app\common\command\rabbtimq;

use app\common\lib\classes\rabbitmq\RabbitMqConnection;
use think\console\Command;
use think\console\Input;
use think\console\Output;
use think\facade\Log;

class Mirror extends Command
{
    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
        $this->setName('mirror');
    }

    protected function execute(Input $input, Output $output)
    {
        // 获取连接对象
        $connection = RabbitMqConnection::getConnection(['host' => '192.168.159.128']);
        // 获取通道
        $channel = $connection->channel();

        // 声明队列
        $queue = 'mirror_hello';
        $channel->queue_declare($queue, false, true, false, false);

        echo ' [*] Waiting for messages. To exit press Ctrl+C', "\n";

        // 回调函数
        $callback = function ($msg) {
            echo " [x] 镜像集群消费者：", $msg->body, "\n";
            $msg->ack();
        };

        // 消费信息
        $channel->basic_consume($queue, '', false, false, false, false, $callback);

        // 监听通道消息，这里没有的话，消费完消息就会自动退出
        while (count($channel->callbacks)) {
            $channel->wait();
        }

        // 关闭连接
        RabbitMqConnection::closeConnectionAndChannel($connection, $channel);
    }

}
